// AAZLI INDUSTRIES — Product Catalog Data
// To add products later, append new objects to AAZLI_PRODUCTS (and a category to
// AAZLI_CATEGORIES if needed). No other code changes are required — pages render
// dynamically from this file.

window.AAZLI_CATEGORIES = [
  { slug: 'tshirts',   name: 'T-Shirts',              count: '5 products', swatch: 'linear-gradient(135deg,#F0721F,#DE1E74)' },
  { slug: 'hoodies',   name: 'Hoodies & Sweatshirts',  count: '4 products', swatch: 'linear-gradient(135deg,#DE1E74,#5B2A8C)' },
  { slug: 'activewear',name: 'Activewear & Sportswear',count: '5 products', swatch: 'linear-gradient(135deg,#F5A82A,#F0721F)' },
  { slug: 'streetwear',name: 'Streetwear Essentials',  count: '4 products', swatch: 'linear-gradient(135deg,#5B2A8C,#19141F)' },
  { slug: 'bottoms',   name: 'Joggers & Bottoms',      count: '4 products', swatch: 'linear-gradient(135deg,#F0721F,#5B2A8C)' },
  { slug: 'kids',      name: 'Kidswear',               count: '4 products', swatch: 'linear-gradient(135deg,#F5A82A,#DE1E74)' },
];

window.AAZLI_PRODUCTS = [
  {
    id: 'classic-crew-tshirt',
    name: 'Classic Crew Neck T-Shirt',
    category: 'T-Shirts', categorySlug: 'tshirts', featured: true,
    swatch: 'linear-gradient(135deg,#F0721F,#DE1E74)',
    short: 'A wardrobe staple built for private-label programs — clean fit, durable stitching.',
    description: 'A versatile everyday tee designed as a base canvas for your brand. Built on a mid-weight cotton platform that holds print and embroidery well, with a true-to-size crew fit suited to both basics lines and graphic drops.',
    material: '100% combed cotton, 180 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Reinforced shoulder and neck seams', 'Pre-shrunk fabric option available', 'Consistent fit across size run', 'Print- and embroidery-ready surface'],
    customization: ['Fabric weight', 'Neck style', 'Screen print', 'Embroidery', 'Woven label', 'Hang tag & packaging'],
  },
  {
    id: 'oversized-tshirt',
    name: 'Oversized Drop-Shoulder Tee',
    category: 'T-Shirts', categorySlug: 'tshirts', featured: true,
    swatch: 'linear-gradient(135deg,#DE1E74,#F5A82A)',
    short: 'Streetwear-driven silhouette with a dropped shoulder and boxy body.',
    description: 'An oversized, drop-shoulder tee for streetwear and fashion-led private label brands. The boxy block and extended shoulder line are pattern-adjustable to match your house fit.',
    material: '100% cotton, 220 GSM heavyweight jersey', sizes: 'S – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Adjustable drop-shoulder pattern', 'Boxy, relaxed body block', 'Ribbed or raw-edge neckline options', 'Suited for oversized graphic placement'],
    customization: ['Silhouette adjustment', 'Fabric selection', 'All-over print', 'Custom labeling', 'Retail-ready packaging'],
  },
  {
    id: 'longsleeve-tshirt',
    name: 'Long Sleeve Tee',
    category: 'T-Shirts', categorySlug: 'tshirts',
    swatch: 'linear-gradient(135deg,#5B2A8C,#DE1E74)',
    short: 'A transitional-season layering piece for basics and streetwear ranges alike.',
    description: 'A long-sleeve tee built to extend a T-shirt program into cooler seasons. Works as a standalone piece or a base layer within a streetwear or activewear collection.',
    material: '95% cotton / 5% elastane, 200 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Ribbed cuffs for shape retention', 'Layer-friendly fit', 'Consistent sizing across the tee family'],
    customization: ['Cuff style', 'Fabric weight', 'Print & embroidery', 'Custom labeling'],
  },
  {
    id: 'polo-tshirt',
    name: 'Pique Polo Shirt',
    category: 'T-Shirts', categorySlug: 'tshirts',
    swatch: 'linear-gradient(135deg,#F5A82A,#5B2A8C)',
    short: 'Smart-casual polo for corporate, workwear and uniform private-label orders.',
    description: 'A pique-knit polo suited to corporate uniform programs, promotional merchandise, and smart-casual private-label collections.',
    material: '100% cotton pique, 220 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Structured collar', 'Reinforced placket and buttons', 'Suited for embroidered logo placement'],
    customization: ['Collar & cuff style', 'Button color', 'Embroidery', 'Corporate branding packages'],
  },
  {
    id: 'pullover-hoodie',
    name: 'Pullover Hoodie',
    category: 'Hoodies & Sweatshirts', categorySlug: 'hoodies', featured: true,
    swatch: 'linear-gradient(135deg,#5B2A8C,#19141F)',
    short: 'Heavyweight fleece hoodie, the anchor piece of most private-label ranges.',
    description: 'A heavyweight pullover hoodie built as the anchor product for streetwear, activewear and lifestyle private-label ranges. Fleece weight, hood construction and fit are all adjustable to your spec.',
    material: '80% cotton / 20% polyester fleece, 320 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Adjustable fleece weight', 'Double-layered hood', 'Kangaroo pocket', 'Ribbed cuffs and hem'],
    customization: ['Hood lining', 'Drawcord color', 'Embroidery & puff print', 'Woven neck label', 'Branded packaging'],
  },
  {
    id: 'zip-hoodie',
    name: 'Full-Zip Hoodie',
    category: 'Hoodies & Sweatshirts', categorySlug: 'hoodies', featured: true,
    swatch: 'linear-gradient(135deg,#19141F,#DE1E74)',
    short: 'Layer-friendly zip-through hoodie for activewear and streetwear lines.',
    description: 'A zip-through hoodie designed for layering across activewear and streetwear ranges. Zipper hardware, pocket configuration and hood shape are all specifiable.',
    material: '80% cotton / 20% polyester fleece, 300 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Full-length zip with custom pull tab', 'Side seam or kangaroo pocket options', 'Adjustable drawcord hood'],
    customization: ['Zipper color & branding', 'Pocket style', 'Fabric weight', 'Custom labeling'],
  },
  {
    id: 'crewneck-sweatshirt',
    name: 'Crewneck Sweatshirt',
    category: 'Hoodies & Sweatshirts', categorySlug: 'hoodies',
    swatch: 'linear-gradient(135deg,#F0721F,#19141F)',
    short: 'A clean, hood-free alternative for minimal streetwear and basics drops.',
    description: 'A crewneck sweatshirt for brands that want the same fleece feel as a hoodie without the hood — popular in minimal streetwear and collegiate-inspired collections.',
    material: '80% cotton / 20% polyester fleece, 280 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Ribbed crew collar, cuffs and hem', 'Adjustable fleece weight', 'Print- and embroidery-ready chest and back'],
    customization: ['Fabric weight', 'Rib color-blocking', 'Print & embroidery', 'Custom labeling'],
  },
  {
    id: 'performance-tee',
    name: 'Performance Training Tee',
    category: 'Activewear & Sportswear', categorySlug: 'activewear', featured: true,
    swatch: 'linear-gradient(135deg,#F5A82A,#F0721F)',
    short: 'Moisture-wicking training tee for activewear and team-sport private label.',
    description: 'A performance tee engineered for movement — built on moisture-wicking, stretch-capable fabric for training, athleisure and team-sport private-label programs.',
    material: '100% polyester interlock, moisture-wicking finish', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Moisture-wicking fabric option', '4-way stretch capability', 'Flatlock seams to reduce chafing', 'Breathable mesh panel option'],
    customization: ['Fabric technology', 'Panel construction', 'Sublimation print', 'Team/brand labeling'],
  },
  {
    id: 'training-jacket',
    name: 'Training Track Jacket',
    category: 'Activewear & Sportswear', categorySlug: 'activewear',
    swatch: 'linear-gradient(135deg,#F0721F,#F5A82A)',
    short: 'Lightweight track jacket for athleisure and sports-brand private label.',
    description: 'A lightweight training jacket suited to athleisure and sports-brand ranges, with a fit and finish tailored for movement.',
    material: '92% polyester / 8% spandex stretch-woven', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Stand collar with zip closure', 'Zippered side pockets', 'Stretch-woven or knit fabric options'],
    customization: ['Colorblocking', 'Zipper hardware', 'Sublimation & embroidery', 'Team kits'],
  },
  {
    id: 'sports-bra',
    name: 'Compression Sports Top',
    category: 'Activewear & Sportswear', categorySlug: 'activewear',
    swatch: 'linear-gradient(135deg,#DE1E74,#F5A82A)',
    short: 'Support-focused compression top for women\u2019s activewear ranges.',
    description: 'A compression sports top designed as an entry point into a women\u2019s activewear private-label range, built on supportive, stretch-capable fabric.',
    material: '88% nylon / 12% spandex compression knit', sizes: 'XS – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Medium-to-high support construction', '4-way stretch fabric', 'Flatlock seaming'],
    customization: ['Support level', 'Strap style', 'Print & panel color', 'Custom labeling'],
  },
  {
    id: 'boxy-hoodie-streetwear',
    name: 'Boxy Streetwear Hoodie',
    category: 'Streetwear Essentials', categorySlug: 'streetwear', featured: true,
    swatch: 'linear-gradient(135deg,#19141F,#5B2A8C)',
    short: 'Heavyweight, boxy-fit hoodie built for limited-drop streetwear labels.',
    description: 'A heavyweight, boxy-fit hoodie built for limited-drop streetwear labels that need a distinctive silhouette and premium hand-feel at low minimums.',
    material: '100% cotton brushed fleece, 400 GSM', sizes: 'S – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Boxy, dropped-shoulder block', 'Heavyweight brushed fleece option', 'Oversized kangaroo pocket'],
    customization: ['Silhouette & block', 'Fleece weight', 'Puff print, embroidery, patches', 'Premium packaging'],
  },
  {
    id: 'utility-cargo',
    name: 'Utility Cargo Pant',
    category: 'Streetwear Essentials', categorySlug: 'streetwear',
    swatch: 'linear-gradient(135deg,#5B2A8C,#F0721F)',
    short: 'Multi-pocket cargo pant for streetwear and utility-driven collections.',
    description: 'A multi-pocket cargo pant designed for streetwear and utility-inspired private-label collections, with adjustable pocket count and placement.',
    material: '98% cotton / 2% spandex twill', sizes: '28 – 40', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Adjustable pocket configuration', 'Reinforced stitching at stress points', 'Adjustable waist and hem options'],
    customization: ['Pocket layout', 'Fabric & wash', 'Hardware branding', 'Custom labeling'],
  },
  {
    id: 'joggers',
    name: 'Fleece Joggers',
    category: 'Joggers & Bottoms', categorySlug: 'bottoms', featured: true,
    swatch: 'linear-gradient(135deg,#F0721F,#5B2A8C)',
    short: 'Tapered fleece jogger — the standard bottoms pairing for hoodie sets.',
    description: 'A tapered fleece jogger designed to pair with the hoodie and sweatshirt range as a matching-set offer, with an elastic-and-drawcord waistband.',
    material: '80% cotton / 20% polyester fleece, 300 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Elastic waistband with drawcord', 'Tapered leg with ribbed cuff', 'Side seam pockets'],
    customization: ['Fabric weight', 'Cuff style', 'Set matching with hoodies', 'Custom labeling'],
  },
  {
    id: 'lounge-pants',
    name: 'Loungewear Pants',
    category: 'Joggers & Bottoms', categorySlug: 'bottoms',
    swatch: 'linear-gradient(135deg,#F5A82A,#5B2A8C)',
    short: 'Soft-hand loungewear pant for comfort-led private-label ranges.',
    description: 'A soft-hand loungewear pant for brands building a comfort-focused, at-home category alongside their core apparel range.',
    material: '95% cotton / 5% elastane brushed jersey', sizes: 'XS – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Relaxed, straight-leg fit', 'Soft-brushed interior option', 'Elastic waistband'],
    customization: ['Fabric hand-feel', 'Fit adjustment', 'Print & embroidery', 'Custom labeling'],
  },
  {
    id: 'kids-tshirt-set',
    name: 'Kids\u2019 T-Shirt & Jogger Set',
    category: 'Kidswear', categorySlug: 'kids',
    swatch: 'linear-gradient(135deg,#F5A82A,#DE1E74)',
    short: 'Matching kids\u2019 tee and jogger set for family and kidswear private label.',
    description: 'A matching tee-and-jogger set sized for kidswear private-label programs, built with the same customization and branding options as the adult range.',
    material: '100% combed cotton, 180 GSM', sizes: '2T – 14', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Soft, skin-friendly fabric option', 'Reinforced seams for durability', 'Matching set sizing'],
    customization: ['Fabric selection', 'Print & embroidery', 'Packaging as a set'],
  },
  {
    id: 'henley-tshirt',
    name: 'Henley Neck Tee',
    category: 'T-Shirts', categorySlug: 'tshirts',
    swatch: 'linear-gradient(135deg,#F5A82A,#DE1E74)',
    short: 'A button-placket alternative to the crew tee for elevated basics lines.',
    description: 'A henley-neck tee that gives a basics range a more elevated, textured alternative to a standard crew neck — popular with premium streetwear and lifestyle labels.',
    material: '100% cotton slub jersey, 200 GSM', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['3-button placket', 'Garment-dyed fabric option', 'Reinforced collar band'],
    customization: ['Button color', 'Placket length', 'Fabric wash', 'Custom labeling'],
  },
  {
    id: 'oversized-hoodie',
    name: 'Oversized Fleece Hoodie',
    category: 'Hoodies & Sweatshirts', categorySlug: 'hoodies',
    swatch: 'linear-gradient(135deg,#F0721F,#19141F)',
    short: 'Extended-length, dropped-shoulder hoodie for fashion-led ranges.',
    description: 'An oversized hoodie with an extended body length and dropped shoulder, built for brands wanting a distinct fashion silhouette rather than a standard athletic fit.',
    material: '70% cotton / 30% polyester fleece, 340 GSM', sizes: 'S – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Extended body length', 'Dropped, extended shoulder seam', 'Oversized hood with adjustable drawcord'],
    customization: ['Body length', 'Fleece weight', 'Embroidery & puff print', 'Premium packaging'],
  },
  {
    id: 'performance-leggings',
    name: 'Performance Leggings',
    category: 'Activewear & Sportswear', categorySlug: 'activewear', featured: true,
    swatch: 'linear-gradient(135deg,#DE1E74,#5B2A8C)',
    short: 'High-waist, four-way stretch leggings for training and athleisure ranges.',
    description: 'High-waist performance leggings built on a four-way stretch, squat-proof fabric — a core piece for any women\u2019s activewear or athleisure private-label range.',
    material: '78% nylon / 22% spandex, brushed-back knit', sizes: 'XS – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['High-rise, squat-proof waistband', 'Four-way stretch fabric', 'Flatlock seaming', 'Optional side pocket'],
    customization: ['Waistband height', 'Panel colorblocking', 'Sublimation print', 'Custom labeling'],
  },
  {
    id: 'windbreaker-jacket',
    name: 'Lightweight Windbreaker',
    category: 'Activewear & Sportswear', categorySlug: 'activewear',
    swatch: 'linear-gradient(135deg,#F5A82A,#5B2A8C)',
    short: 'Packable, water-resistant jacket for running and training lines.',
    description: 'A lightweight, packable windbreaker with a water-resistant finish, suited to running and training-focused activewear ranges as a light outer layer.',
    material: '100% polyester ripstop, DWR coating', sizes: 'XS – 2XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Water-resistant DWR coating', 'Packable into own pocket', 'Reflective trim option'],
    customization: ['Colorblocking', 'Reflective branding', 'Zipper hardware', 'Custom labeling'],
  },
  {
    id: 'utility-vest',
    name: 'Sleeveless Utility Vest',
    category: 'Streetwear Essentials', categorySlug: 'streetwear', featured: true,
    swatch: 'linear-gradient(135deg,#19141F,#F0721F)',
    short: 'Multi-pocket utility vest, a statement layering piece for streetwear drops.',
    description: 'A sleeveless utility vest with a multi-pocket layout, designed as a statement layering piece for streetwear brands building out a fuller collection beyond tees and hoodies.',
    material: '100% cotton canvas, 280 GSM', sizes: 'S – 2XL', moq: '100 pieces per style/color', leadTime: '18–25 working days after sample approval',
    features: ['Multi-pocket utility layout', 'Adjustable side straps', 'Reinforced bar-tack stitching'],
    customization: ['Pocket configuration', 'Hardware finish', 'Fabric & wash', 'Custom labeling'],
  },
  {
    id: 'puffer-jacket',
    name: 'Quilted Puffer Jacket',
    category: 'Streetwear Essentials', categorySlug: 'streetwear',
    swatch: 'linear-gradient(135deg,#5B2A8C,#DE1E74)',
    short: 'Insulated puffer for cold-season streetwear and outerwear drops.',
    description: 'A quilted, insulated puffer jacket for brands extending into cold-season outerwear, with a boxy or fitted silhouette available depending on your spec.',
    material: 'Polyester shell with synthetic fill insulation', sizes: 'S – 2XL', moq: '80 pieces per style/color', leadTime: '20–28 working days after sample approval',
    features: ['Quilted panel construction', 'Insulated fill for warmth', 'Storm cuffs and adjustable hem'],
    customization: ['Silhouette & fit', 'Fill weight', 'Lining color', 'Custom labeling'],
  },
  {
    id: 'track-pants',
    name: 'Track Pants with Side Stripe',
    category: 'Joggers & Bottoms', categorySlug: 'bottoms',
    swatch: 'linear-gradient(135deg,#DE1E74,#19141F)',
    short: 'Classic side-stripe track pant for sport-inspired streetwear ranges.',
    description: 'A classic track pant with a side-stripe detail, popular across sport-inspired streetwear and retro athleisure collections.',
    material: '100% polyester tricot', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Contrast side-stripe detail', 'Elastic waistband with drawcord', 'Ankle zip option'],
    customization: ['Stripe color & width', 'Fabric finish', 'Ankle style', 'Custom labeling'],
  },
  {
    id: 'training-shorts',
    name: 'Training Shorts',
    category: 'Joggers & Bottoms', categorySlug: 'bottoms',
    swatch: 'linear-gradient(135deg,#F5A82A,#F0721F)',
    short: 'Lightweight training shorts for activewear and team-sport programs.',
    description: 'Lightweight training shorts built for movement, suited to activewear ranges, team-sport kits, and summer streetwear drops alike.',
    material: '100% polyester interlock, moisture-wicking finish', sizes: 'XS – 3XL', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Moisture-wicking fabric', 'Elastic waistband with internal drawcord', 'Side seam pockets'],
    customization: ['Inseam length', 'Fabric technology', 'Sublimation print', 'Team/brand labeling'],
  },
  {
    id: 'kids-hoodie',
    name: 'Kids\u2019 Pullover Hoodie',
    category: 'Kidswear', categorySlug: 'kids', featured: true,
    swatch: 'linear-gradient(135deg,#F0721F,#F5A82A)',
    short: 'Scaled-down version of the adult hoodie, sized for kidswear ranges.',
    description: 'A pullover hoodie scaled and softened for kidswear private-label programs, using the same customization options as the adult range so sibling or family sets are easy to produce.',
    material: '80% cotton / 20% polyester fleece, 280 GSM', sizes: '2T – 14', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Soft, skin-friendly fleece', 'Reinforced seams for durability', 'Kangaroo pocket'],
    customization: ['Fabric weight', 'Print & embroidery', 'Matching adult/kids sets'],
  },
  {
    id: 'kids-shorts-set',
    name: 'Kids\u2019 Tee & Shorts Set',
    category: 'Kidswear', categorySlug: 'kids',
    swatch: 'linear-gradient(135deg,#DE1E74,#F0721F)',
    short: 'Matching summer set for kidswear private-label ranges.',
    description: 'A matching tee-and-shorts set for warmer-season kidswear ranges, packaged and labeled as a set for retail or e-commerce sale.',
    material: '100% combed cotton, 180 GSM', sizes: '2T – 14', moq: '100 pieces per set', leadTime: '15–20 working days after sample approval',
    features: ['Soft, breathable cotton', 'Elastic waistband on shorts', 'Matching set sizing'],
    customization: ['Fabric selection', 'Print & embroidery', 'Set packaging'],
  },
  {
    id: 'kids-leggings',
    name: 'Kids\u2019 Leggings',
    category: 'Kidswear', categorySlug: 'kids',
    swatch: 'linear-gradient(135deg,#5B2A8C,#F5A82A)',
    short: 'Stretch leggings for kidswear and family activewear ranges.',
    description: 'Stretch leggings sized for a kidswear range, sharing the same stretch-fabric platform as the adult performance leggings for brands offering family activewear sets.',
    material: '90% cotton / 10% spandex jersey', sizes: '2T – 14', moq: '100 pieces per style/color', leadTime: '15–20 working days after sample approval',
    features: ['Soft stretch waistband', 'Flat seams for comfort', 'Durable, wash-resistant fabric'],
    customization: ['Fabric selection', 'Print patterns', 'Matching family sets'],
  },
];
